#app.yaml
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: 
  CLOUD_SQL_PASSWORD: 
  CLOUD_SQL_DATABASE_NAME:  
  CLOUD_SQL_CONNECTION_NAME: istvari-project-5001:us-east1:istvaridb0001
  
  #sustained-drake-290710:us-central1:flask-sample

handlers:
# - url: /static
#   static_dir: static

- url: /.*
  script: auto